using System;

namespace PatientRecords.AutoGenerated.HelperClasses.Interfaces
{
    public interface ITextTemplate
    {
        string TransformText() => throw new NotImplementedException();
    }
}
