using PatientRecords.AutoGenerated.HelperClasses;
using PatientRecords.AutoGenerated.HelperClasses.Interfaces;
using System;
using System.Collections.Generic;

namespace PatientRecords.AutoGenerated.GeneratedStructure.ClassesGeneratedStructure
{
    public partial class EntitiesContextTemplate : ITextTemplate
    {

        /// <summary>
        /// Entity's Namespace.
        /// </summary>
        public string NameSpace { get; }

        /// <summary>
        /// Table Data.
        /// </summary>
        public List<Type> Entities { get; }

        /// <summary>
        /// Context Name.
        /// </summary>
        public string ContextName { get; }

        /// <summary>
        /// Context Name.
        /// </summary>
        public string EntityConfigurationConvention { get; }

        /// <summary>
        /// Creates an Instance of TableEntityTemplate.
        /// </summary>
        /// <param name="nameSpace">Entity's Namespace.</param>
        /// <param name="table">Table Data.</param>
        public EntitiesContextTemplate(string nameSpace, string contextName, string entityConfigurationConvention, List<Type> entities)
            => (NameSpace, ContextName, EntityConfigurationConvention, Entities) = (nameSpace, contextName, entityConfigurationConvention, entities);


    }
}
