using PatientRecords.AutoGenerated.HelperClasses;
using PatientRecords.AutoGenerated.HelperClasses.Interfaces;
using System;
using System.Collections.Generic;

namespace PatientRecords.AutoGenerated.GeneratedStructure.ClassesGeneratedStructure
{
    public partial class EntitiesExtensionTemplate : ITextTemplate
    {

        /// <summary>
        /// Entity's Namespace.
        /// </summary>
        public string NameSpace { get; }

        /// <summary>
        /// Table Data.
        /// </summary>
        public List<Type> Entities { get; }

        /// <summary>
        /// Context Name.
        /// </summary>
        public string ExtensiontName { get; }

        /// <summary>
        /// Creates an Instance of TableEntityTemplate.
        /// </summary>
        /// <param name="nameSpace">Entity's Namespace.</param>
        /// <param name="table">Table Data.</param>
        public EntitiesExtensionTemplate(string nameSpace, string extensiontName, List<Type> entities)
            => (NameSpace, ExtensiontName, Entities) = (nameSpace, extensiontName, entities);


    }
}
