using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PatientRecords.AutoGenerated
{
    public interface ITextTemplate
    {
        string TransformText() => throw new NotImplementedException();
    }
}
