using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using PatientRecords.AutoGenerated.GeneratedStructure.ClassesGeneratedStructure;
using PatientRecords.AutoGenerated.HelperClasses;
using PatientRecords.AutoGenerated.HelperClasses.Interfaces;
using PatientRecords.DataLayer.DataUtilities.DBContext;

namespace PatientRecords.AutoGenerated
{
    public class Program
    {
        private const string BL_PROJECT_NAME = "PatientRecords.BLLayer";
        private const string DATA_PROJECT_NAME = "PatientRecords.DataLayer";
        private const string GENERATED_FOLDER_NAME = "Generated";

        private static void Main()
        {

            Assembly assembly = Assembly.Load("PatientRecords.DataLayer");
            var entities = assembly.GetTypes().Where(s => s.Namespace == "PatientRecords.DataLayer.Data.Entities").ToList();

            GenerateEntitiesContext(entities);

            foreach (Type type in entities)
            {
                TableInfo tableInfo = new TableInfo()
                {
                    Type = type,
                    Properties = type.GetProperties().Where(s => s.DeclaringType.Name == type.Name).ToArray(),
                    Context = typeof(MainContext),
                };

                GenerateEntityConfiguration(type, tableInfo);
                GenerateEntityIRepositry(type, tableInfo);
                GenerateEntityRepositry(type, tableInfo);
                GenerateEntityDTO(type,tableInfo);
                GenerateEntityView(type, tableInfo);
                GenerateEntityIQueryService(type, tableInfo);
                GenerateEntityQueryService(type, tableInfo);
            }
        
        }

        private static void GenerateEntityDTO(Type type,TableInfo tableInfo)
        {
            var folderName = "EntityDTOs";
            var fileConvention = "DTO.Generated.cs";
            string startupPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             BL_PROJECT_NAME,
                                             folderName,
                                             GENERATED_FOLDER_NAME,
                                             type.Name + fileConvention);
            ITextTemplate template = new EntitiesDTOTemplate(BL_PROJECT_NAME + "." + folderName, tableInfo);
            System.IO.File.WriteAllText(startupPath, template.TransformText().RemoveGarbageLinesFromString());
        }

        private static void GenerateEntityView(Type type, TableInfo tableInfo)
        {
            var folderName = "EntityViews";
            var fileConvention = "View.Generated.cs";
            string fullPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             BL_PROJECT_NAME,
                                             folderName,
                                             GENERATED_FOLDER_NAME,
                                             type.Name + fileConvention);
            ITextTemplate template = new EntitiesViewTemplate(BL_PROJECT_NAME + "." + folderName, tableInfo);
            System.IO.File.WriteAllText(fullPath, template.TransformText().RemoveGarbageLinesFromString());
        }

        private static void GenerateEntityQueryService(Type type, TableInfo tableInfo)
        {
            var folderName = "QueryServices";
            var fileConvention = "QueryService.cs";
            string fullPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             BL_PROJECT_NAME,
                                             folderName,
                                             type.Name + fileConvention);
            if (!File.Exists(fullPath))
            {
                ITextTemplate template = new EntitiesQueryServiceTemplate(BL_PROJECT_NAME + "." + folderName, tableInfo);
                System.IO.File.WriteAllText(fullPath, template.TransformText().RemoveGarbageLinesFromString());
            }
        }

        private static void GenerateEntityIQueryService(Type type, TableInfo tableInfo)
        {
            var folderName = Path.Combine("QueryServices","Interfaces");
            var firstFileConvention = "I";
            var lastFileConvention = "QueryService.cs";
            string fullPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             BL_PROJECT_NAME,
                                             folderName,
                                             firstFileConvention + type.Name + lastFileConvention);
            if (!File.Exists(fullPath))
            {
                ITextTemplate template = new EntitiesIQueryServiceTemplate(BL_PROJECT_NAME + "." + folderName.Replace("\\", "."), tableInfo);
                System.IO.File.WriteAllText(fullPath, template.TransformText().RemoveGarbageLinesFromString());
            }
        }

        private static void GenerateEntityIRepositry(Type type, TableInfo tableInfo)
        {
            var folderName = Path.Combine("Data", "Repositries", "Interfaces");
            var firstFileConvention = "I";
            var lastFileConvention = "Repositry.cs";
            string fullPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             DATA_PROJECT_NAME,
                                             folderName,
                                             firstFileConvention + type.Name + lastFileConvention);
            if (!File.Exists(fullPath))
            {
                ITextTemplate template = new EntitiesIRepositryTemplate(DATA_PROJECT_NAME + "." + folderName.Replace("\\", "."), tableInfo);
                System.IO.File.WriteAllText(fullPath, template.TransformText().RemoveGarbageLinesFromString());
            }
        }

        private static void GenerateEntityRepositry(Type type, TableInfo tableInfo)
        {
            var folderName = Path.Combine("Data", "Repositries"); 
            var fileConvention = "Repositry.cs";
            string fullPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             DATA_PROJECT_NAME,
                                             folderName,
                                             type.Name + fileConvention);
            if (!File.Exists(fullPath))
            {
                ITextTemplate template = new EntitiesRepositryTemplate(DATA_PROJECT_NAME + "." + folderName.Replace("\\", "."), tableInfo);
                System.IO.File.WriteAllText(fullPath, template.TransformText().RemoveGarbageLinesFromString());
            }
        }

        private static void GenerateEntityConfiguration(Type type, TableInfo tableInfo)
        {
            var folderName = Path.Combine("Data", "Configuration");
            var fileConvention = "Configuration.cs";
            string fullPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             DATA_PROJECT_NAME,
                                             folderName,
                                             type.Name + fileConvention);
            if (!File.Exists(fullPath))
            {
                ITextTemplate template = new EntitiesConfigurationTemplate(DATA_PROJECT_NAME + "." + folderName.Replace("\\", "."), tableInfo);
                System.IO.File.WriteAllText(fullPath, template.TransformText().RemoveGarbageLinesFromString());
            }
        }

        private static void GenerateEntitiesContext(List<Type> entities)
        {
            var folderName = Path.Combine("DataUtilities", "DBContext");
            var fileName = "MainContext.cs";
            string fullPath = Path.Combine(Directory.GetParent(System.IO.Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName,
                                             DATA_PROJECT_NAME,
                                             folderName,
                                             fileName);
            ITextTemplate template = new EntitiesContextTemplate(DATA_PROJECT_NAME + "." + folderName.Replace("\\", "."),
                                                                 "MainContext",
                                                                 "Configuration", 
                                                                 entities);
            System.IO.File.WriteAllText(fullPath, template.TransformText().RemoveGarbageLinesFromString());
        }
    }
}
