using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace PatientRecords.AutoGenerated
{
    public class TableInfo
    {
        public Type Type { get; set; }

        public PropertyInfo[] Properties { get; set; }
 
    }
}
