using System;
using System.Reflection;


namespace PatientRecords.AutoGenerated.HelperClasses
{
    public class TableInfo
    {
        public Type Type { get; set; }

        public PropertyInfo[] Properties { get; set; }
 
        public Type Context { get; set; }
    }
}
