using PatientRecords.BLLayer.BLUtilities.HelperServices.Interfaces;
using System;
using System.Reflection;


namespace PatientRecords.AutoGenerated.HelperClasses
{
    public class TableInfo
    {
        public Type Type { get; set; }

        public PropertyInfo[] Properties { get; set; }
 
        public Type Context { get; set; }

        public Type ServiceBuildException { get; set; }

        public Type CommonServices { get; set; }

        public Type PaginationHelperServices { get; set; }

        public Type Mapper { get; set; }

        public Type UriService { get; set; }

        public Type HttpContextAccessor { get; set; }

        public Type ApiExceptionBuilder { get; set; }
    }
}
